{% set name = "azure-search-documents" %}
{% set version = "11.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 13883d12c833b66546c188cce847de6fa67b83545cb21163d8956ac031e53cf8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - typing-extensions >=4.6.0
    - python >=3.7
    - azure-core >=1.28.0
    - azure-common >=1.1
    - isodate >=0.6.0

test:
  imports:
    - azure.search.documents
    - azure.search.documents._generated
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/search/azure-search-documents
  summary: Microsoft Azure Cognitive Search Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
